
[[apps]]
name = "\n:: System Utils ::\n"

# broken on v11
[[apps]]
name = "Dingux Commander"
cmd = "dinguxcommander"

[[apps]]
name = "System Update"
cmd = "sudo pacman -Syu --noconfirm"
term = true

#[[apps]]
#name = "Install package(s) from USB"
#cmd = "sudo mount /dev/sda1 /mnt && sudo pacman -U --noconfirm /mnt/pkg/*.xz; sudo umount /dev/sda1"
#term = true
#
#[[apps]]
#name = "Rsync roms from USB"
#cmd = "sudo mount /dev/sda1 /mnt && rsync -av /mnt/roms/* /roms/; sudo umount /dev/sda1"
#term = true

[[apps]]
name = "neofetch"
cmd = "neofetch --ascii_distro Arch_small"
term = true

[[apps]]
name = "Autostart RetroLauncher"
cmd = "sudo systemctl disable emulationstation; sudo systemctl enable retrolauncher"
term = true

[[apps]]
name = "Autostart Emulation Station"
cmd = "sudo systemctl disable retrolauncher; sudo systemctl enable emulationstation"
term = true


